fix exit command

diff --git a/bin/correct-git-email b/bin/correct-git-email
--- a/bin/correct-git-email
+++ b/bin/correct-git-email
@@ -12,9 +12,9 @@ EOF
 }
 
 if [ $# -ne 2 ]; then
-    logger.error "Required old and new email."
-    usage
-    exit false
+  logger.error "Required old and new email."
+  usage
+  false || exit
 fi
 
 OLD_EMAIL=$1 NEW_EMAIL=$2 git filter-branch --commit-filter '
@@ -25,4 +25,4 @@ OLD_EMAIL=$1 NEW_EMAIL=$2 git filter-branch --commit-filter '
       git commit-tree "$@";
   else
     git commit-tree "$@";
-  fi' HEAD
+fi' HEAD
